/*SELECT DISTINCT I.REST_ID, 
       I.REST_NAME, 
       I.FOOD_TYPE, 
       I.FAVORITES, 
       I.ADDRESS, 
      AVG(REVIEW_SCORE) OVER(PARTITION BY R.REST_ID) AS "SCORE"
FROM REST_INFO I RIGHT OUTER JOIN REST_REVIEW R
ON I.REST_ID=R.REST_ID;*/

/*SELECT DISTINCT REST_ID, 
REST_NAME, 
FOOD_TYPE,
FAVORITES,  
ADDRESS, 
ROUND(SCORE,2) AS "SCORE"
FROM (SELECT  I.REST_ID, 
       I.REST_NAME, 
       I.FOOD_TYPE, 
       I.FAVORITES, 
       I.ADDRESS, 
      AVG(R.REVIEW_SCORE) OVER(PARTITION BY I.REST_ID) AS "SCORE"
FROM REST_INFO I RIGHT OUTER JOIN REST_REVIEW R
ON I.REST_ID=R.REST_ID
     
     )
     WHERE ADDRESS LIKE '%서울%'
     ORDER BY SCORE DESC, FAVORITES DESC
;*/
SELECT DISTINCT I.REST_ID, 
I.REST_NAME, 
I.FOOD_TYPE,
I.FAVORITES,  
I.ADDRESS, 
SCORE
FROM REST_INFO I, (SELECT REST_ID, 
                  ROUND(AVG(REVIEW_SCORE),2) AS "SCORE"
                  FROM REST_REVIEW
                  GROUP BY REST_ID) R
WHERE I.REST_ID=R.REST_ID
AND I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;