
SELECT DISTINCT P.PRODUCT_ID, 
       P.PRODUCT_NAME, 
   --    O.PRODUCE_DATE,
       SUM(P.PRICE*O.AMOUNT) OVER(PARTITION BY P.PRODUCT_ID) AS TOTAL_SALES
FROM FOOD_PRODUCT P INNER JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE,'YYYY-MM')='2022-05'
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;